# Generated by Django 3.1.7 on 2021-04-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemslist',
            name='image_logo',
            field=models.FileField(blank='True', null='True', upload_to=''),
            preserve_default='True',
        ),
    ]
