# Generated by Django 3.1.7 on 2021-04-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_itemslist_image_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemslist',
            name='image_logo',
            field=models.ImageField(blank='True', null='True', upload_to=''),
        ),
    ]
