# Generated by Django 3.1.7 on 2021-04-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_auto_20210429_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemslist',
            old_name='image_logo',
            new_name='image',
        ),
    ]
