# Generated by Django 3.1.7 on 2021-04-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_auto_20210429_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemslist',
            name='image',
            field=models.FileField(blank='True', null='True', upload_to=''),
        ),
    ]
