# Generated by Django 3.1.7 on 2021-04-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_auto_20210429_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemslist',
            name='image',
            field=models.ImageField(default=2, upload_to='images'),
            preserve_default=False,
        ),
    ]
